# Generated by Django 5.1.2 on 2026-05-02 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('flag_ids', models.JSONField(default=list)),
                ('flag_count', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('file_size', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'flags_report',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='flag',
            new_name='flags_flag_severit_d9d291_idx',
            old_name='flags_flag_sev_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='flag',
            new_name='flags_flag_distric_2f223a_idx',
            old_name='flags_flag_dist_stat_idx',
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
