# Generated by Django 5.1.2 on 2026-05-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0002_add_report_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flag',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='construction_stage',
            field=models.CharField(blank=True, default='', help_text='foundation / walls / roofing / finishing / completed / demolished / none_visible', max_length=64),
        ),
        migrations.AddField(
            model_name='inspection',
            name='estimated_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='occupancy_observed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flag',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_review', 'In Review'), ('confirmed', 'Confirmed Unauthorized'), ('dismissed', 'Dismissed'), ('monitoring', 'Under Monitoring'), ('inaccessible', 'Inaccessible'), ('data_error', 'Data Error'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='verdict',
            field=models.CharField(choices=[('confirmed', 'Confirmed Unauthorized'), ('dismissed', 'Dismissed — False Positive'), ('monitoring', 'Under Monitoring'), ('inaccessible', 'Site Inaccessible'), ('data_error', 'Data Error — Wrong Location')], max_length=32),
        ),
    ]
