# Generated by Django 5.1.2 on 2026-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0004_inspectionphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='distance_to_site_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspector_location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
