# Generated by Django 5.1.2 on 2026-06-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0005_add_inspector_location_to_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='permit_status',
            field=models.CharField(choices=[('authorized', 'Authorized — Active Permit'), ('no_permit', 'No Construction Permit'), ('expired', 'Expired Permit'), ('wrong_category', 'Wrong Permit Category'), ('zone_violation', 'Protected Zone Violation'), ('no_parcel', 'Unregistered Land')], db_index=True, default='no_permit', max_length=32),
        ),
        migrations.AddField(
            model_name='flag',
            name='severity_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
