services:
  - type: web
    name: imbonesha-api
    runtime: docker
    dockerfilePath: api/Dockerfile
    dockerContext: api
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: imbonesha-api.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: imbonesha-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://imbonesha-dashboard.vercel.app
      - key: PERMIT_SERVICE_URL
        value: https://imbonesha-permit.onrender.com
      - key: PERMIT_ADAPTER
        value: mock
      - key: ML_SERVICE_URL
        value: http://localhost:8002
      - key: MINIO_ENDPOINT
        sync: false
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_BUCKET
        value: imbonesha-imagery
      - key: MINIO_SECURE
        value: "True"
      - key: MINIO_PUBLIC_ENDPOINT
        sync: false
      - key: NOTIFICATION_BACKEND
        value: console
      - key: FRONTEND_URL
        value: https://imbonesha-dashboard.vercel.app
    healthCheckPath: /health/

  - type: web
    name: imbonesha-permit
    runtime: docker
    dockerfilePath: mock-services/permit-service/Dockerfile
    dockerContext: mock-services/permit-service
    envVars:
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health

  - type: redis
    name: imbonesha-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction
