# Generated by Django 5.1.2 on 2026-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
