# Generated by Django 5.1.2 on 2026-04-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagery', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='imagescene',
            new_name='imagery_ima_aoi_id_a570ac_idx',
            old_name='imagery_ima_aoi_cap_idx',
        ),
        migrations.RenameIndex(
            model_name='imagescene',
            new_name='imagery_ima_source_7a941c_idx',
            old_name='imagery_ima_source_idx',
        ),
        migrations.AddField(
            model_name='imagescene',
            name='metadata',
            field=models.JSONField(blank=True, default=None, help_text='Optional scene metadata (geo-transform, acquisition params).', null=True),
        ),
    ]
